#ifndef EXCELREADER_GLOBAL_H
#define EXCELREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXCELREADER_LIBRARY)
#  define EXCELREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXCELREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXCELREADER_GLOBAL_H
